### ISSUE TITLE
Alexey Novak: new volunteer via Mozilla Science Lab Collaborate 

### ISSUE THREAD

**Issue by anvk** [JaredHawkins/TweetGeoViz#10]
Hi there.

I would love to contribute to the project. I have FullStack JavaScript experience and interested in this project.

**Comment by JaredHawkins** [comment]
Hi Alexey,

We would love to have you!  A few comp sci students from Olin College are
also working on it, though I am not sure if they have pushed any changes
yet.  Would you like to connect with the team or would you prefer to do
some work on your own?

Best,
Jared

**Comment by anvk** [comment]
Hey Jared,

I put a pull request to fix up some basic issues for the initial code you setup.
Yeah it is always fun when more people are participating to the project but I do not see any pushes or any commits in the history in this repo.
Isn't it the main repo for the project ?

**Comment by JaredHawkins** [comment]
Hey Alexey,

Sorry, I saw the pull request but thought I had already approved it.  It
has been merged!

This is the main repo, though the project was stagnant for some time and
has just started up.  I do a lot of similar work in my main research, but
the goal here was to open-source a specific visualization / cluster
identification aspect for us and others to use.

Can I have your main contact, so I can put you in touch with the rest of
the team?

Best,
Jared

**Comment by anvk** [comment]
For sure Jared. You can always find my main email in my GitHub profile https://github.com/anvk
but I'm also reachable at abovebluesky@gmail.com

I'm excited to help out and be part of this OSS project since it sounds like lots of fun and also could be useful for people out there.

To be honest I was about to create a GitHub issue/task "Project Planning" and to suggest some ideas to move the project forward like: start a generic discussion on the project main goal of what we are trying to solve, weekly meetups, project milestones, start a a discussion about UI and UX, others...
What do you think? Or those discussions should be a part of public conversations in IRC or Slacker (or whatever chat system you guys use)

Shoot me an email so we can get in touch.

**Comment by JaredHawkins** [comment]
Hi Alexey,

I think project planning would be helpful.  Thank you!  I'll follow-up with
an email connecting you to the rest of the team.

Best,
Jared
