### ISSUE TITLE
Milap Bhojak: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by milapbhojak** [JaredHawkins/TweetGeoViz#34]
What I've understood about Data science is we are getting a lot of unstructure data but the problem is we really didn't know how to use and how it could help us in real life so our job is to make that data useful by making a data products. I've never thought we could use social media to detect disease epidemics as they emerge. I've found this is the best use of social media so far. I would love to become a part of this project.

Well, I can design data product. I'm a programmer and coding in python since 3 years and familiar with D3.js so I've found this project  would be best fit for me. <p><br><blockquote>This issue was created by @milapbhojak via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by JaredHawkins** [comment]
Hi Milap,

My apologies in taking so long to respond!  I have been traveling and just getting back up to speed.  It is a pleasure to have you join the project!  We had a few students work on this for a Data Science course last semester, and I am trying to get them to upload their code to github.  We don’t necessarily have to build off of that, but are free to create whatever you (and the rest of the team) are interested in working on.  

Can I add you to our Slack group?  If so, what email is best?

Looking forward to working with you!

Best,
Jared

**Comment by milapbhojak** [comment]
Hey Jared,

Yeah, sure add me my email id is milapbhojak dot exe at gmail dot com

-milap :)
