### ISSUE TITLE
Mitchell J Stanton-Cook: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by mscook** [JaredHawkins/TweetGeoViz#35]
I'm a BioDevOp @ The University of Queensland, Brisbane, Australia.
I'm going to work on this project during The Mozilla Science Global Sprint is June 4/5 at our University of Queensland Site.
http://deriv.es<p><br><blockquote>This issue was created by @mscook via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by JaredHawkins** [comment]
My apologies in taking so long to respond!  I have been traveling and just getting back up to speed.  It is a pleasure to have you join the project!  We had a few students work on this for a Data Science course last semester, and I am trying to get them to upload their code to github.  We don’t necessarily have to build off of that, but are free to create whatever you (and the rest of the team) are interested in working on.  

Can I add you to our Slack group?  If so, what email is best?

Looking forward to working with you!

Best,
Jared
