### ISSUE TITLE
Abhiram Ravikumar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by abhi12ravi** [JaredHawkins/TweetGeoViz#37]
Hi all, 

I work on front-end web design, data enthusiast and Python frameworks. I'm comparatively new to JavaScript, hoping to catch on!<p><br><blockquote>This issue was created by @abhi12ravi via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by JaredHawkins** [comment]
Hi Abhiram!

Welcome!  Can you please send me your email so I can add you to our Slack team?

Best,
Jared

**Comment by abhi12ravi** [comment]
Hey Jared!

Thank you. My email is abhi12ravi@gmail.com.
