### ISSUE TITLE
we should add multi-language support for this app

### ISSUE THREAD

**Issue by anvk** [JaredHawkins/TweetGeoViz#53]
I think that we should remove "Keyword Part of Another Word" UI from the sliding panel.

And instead of thinking adding multi-language support to the project.
First we need to think about UI, where to add language selection. I believe it should be either A: a dropdown in the top right corner of the Map. B: In the slide panel

I lean towards (B)

I believe we better add multi-language support earlier than later.

**Comment by carloscarcamo** [comment]
+1 for (B)

**Comment by anvk** [comment]
@carloscarcamo could you please create another pull request adding missing spanish translations ?

**Comment by carloscarcamo** [comment]
sure! but, I have a question, how should new language should be added?
something like: ```http://localhost:8080/spanish``` and what about the view files location?

**Comment by anvk** [comment]
Well if you get the latest master you will see that translations already work. I'm missing spanish labels in `client/src/translations/sp.js` file.

What about URL - it is a good idea but one step at a time. Let's just make proper translations and then we can discuss if we need to express the language in URL as well

**Comment by carloscarcamo** [comment]
Hey, what do you think if we use ```es``` prefix for spanish language instead of ```sp```?, this way we would use the [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) standard to use two-letter codes for indicating a language.

**Comment by JaredHawkins** [comment]
Absolutely agree!

- Jared

On January 11, 2016 at 6:10:43 PM EST, Carlos Cárcamo <notifications@github.com> wrote:Hey, what do you think if we use es  prefix for spanish language instead of sp ?, this way we would use the ISO 639-1 standard to use two-letter codes for indicating a language.  —Reply to this email directly or view it on GitHub.

**Comment by anvk** [comment]
Sounds good. @carloscarcamo could you please fix it as well as put translations into `es.js` file.

**Comment by anvk** [comment]
added language to url
